hmcts/cnp-aks-rbac-pipelines

pipeline.yaml, templates/arm-aks-parameters.json, templates/arm-aks-template.json
RPE-1035 - enable log analytics and diagnostics monitoring
=> RPE-1035 - enable log analytics and diagnostics monitoring 

pipeline-rpe-klawani-uks.yaml
Add new pipeline to create a new AKS cluster for monitoring refinement ticket
```
[ ] Yes
[ x] No
```
=> add new pipeline

scripts/install-flux.sh
Added cluster specific folder for flux
```
[ ] Yes
[x] No
```
=> Added cluster specific folder for flux

scripts/install-flux.sh
add common folder per env
```
[ ] Yes
[x] No
```
=> add common folder per env

templates/appgw-arm.json
https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/79
Add arm template for appgw to AKS
```
[ ] Yes
[x] No
```
=> Add arm template for appgw to AKS

templates/appgw-arm.json
Fixing typo in arm template
```
[ ] Yes
[x] No
```
=> Fixing typo in arm template

templates/arm-vnet-template.json
[AB#137](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/137)
Add SQL and Storage service endpoints to subnets
```
[ ] Yes
[ ] No
```
=> Add required service endpoints to subnets

templates/appgw-arm.json, templates/arm-vnet-template.json
[AB#133](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/133)
=> Refactor subnet resources

scripts/download-helm-pki.sh, scripts/generate-helm-pki.sh, scripts/install-flux.sh, scripts/install-tiller.sh
https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/39
Extracted scripts from https://dev.azure.com/hmcts/_git/CNP?path=%2Fhelm-tls.yaml&version=GBmaster
Reordered arguments , knowing that it will break. Will fix it in UI before merging this PR.  
```
[ ] Yes
[x] No
```
=> Modified scripts to optionally enable helm tls

scripts/create-azure-file-share.sh
https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/164
Add Azure file share for NeuVector persistent storage
```
[ ] Yes
[x] No
```
[AB#164](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/164)
=> Azure file share for NeuVector

scripts/generate-helm-pki.sh
=> Increase helm cert expiry

scripts/install-flux.sh
=> fixing script

scripts/install-tiller.sh
=> Fixing path, script was extracted from a helmdeploy task

scripts/install-tiller.sh
=> trying with different path similar to other files

scripts/install-flux.sh
Adding paths as per the root directory set to pipeline
```
[ ] Yes
[x] No
```
=> Adding paths as per the root directory set to pipeline

scripts/install-sealed-secrets.sh
Adding tls parameters when enabling helm tls . removing default parameters to override them in config . 
```
[ ] Yes
[ ] No
```
=> Add tls params when enabling tls

scripts/install-flux.sh
Enabling TLS on helm operator and removing verify 
```
[ ] Yes
[x] No
```
=> Enabling TLS on helm operator

scripts/install-flux.sh, scripts/install-tiller.sh
Resetting tiller and recreating pods always to enforce any changes done like tls certs.  
```
[ ] Yes
[x] No
```
=> Resetting tiller  and recreating flux pods always

templates/arm-mon-infra.json
-
Removed monitoring action group shortname ag suffix.
```
[ ] Yes
[x] No
```
=> Removed monitoring action group ag suffix.

templates/arm-vnet-template.json
https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/175
Add DNS servers to VNET ARM template
```
[ ] Yes
[x] No
```
[AB#175](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/175)
=> add dns servers to vnet template

scripts/delete-aks-cluster.sh
https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/189
Add delete AKS cluster script
```
[ ] Yes
[x] No
```
[AB#189](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/189)
=> add delete cluster script

azure-pipelines.yml
[AB#206](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/206)
It's not useful...
```
[ ] Yes
[ ] No
```
=> Remove release definition prefix

README.md, azure-pipelines.yml, ci/set-build-pipeline-name.sh
Fixes [AB#207](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/207)
```
[ ] Yes
[ ] No
```
=> Set build name to have PR in it

templates/arm-mon-custom-alerts.json
Add monitoring for Pods restarting several times
```
[ ] Yes
[ x] No
```
=> add alert for pods restarting several times

templates/arm-mon-custom-alerts.json
Signed-off-by: Karim Lawani <k7lawani@gmail.com>
split alerts based on Namespace and change severity level
```
[ ] Yes
[x ] No
```
=> split alerts by severity

templates/arm-mon-custom-alerts.json
update naming
```
[ ] Yes
[x ] No
```
=> Refine monitoring alert

scripts/install-flux.sh
Repointing flux to new folder structure.
```
[ ] Yes
[x] No
```
=> repointing flux to new structure

scripts/install-flux.sh
=> Remove automated overlay folder as flux isn't currently supporting multiple pacthes in single git path

templates/arm-vnet-template.json
Fixes [AB#305](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/305)
Adding no rules to configure default rules in NSGs.
```
[ ] Yes
[x] No
```
=> Adding NSGs for subnets

templates/appgw-arm.json, templates/arm-aks-template.json, templates/arm-vnet-template.json
Fixes [AB#321](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/321)
Fixes [AB#223](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/223)
```
[ ] Yes
[x] No
```
=> Adding diagnostic settings for nsgs

scripts/enable-aks-monitor.sh
Fixing other reference to workspace id, earlier test worked because i didn't delete the id from variable group.
```
[ ] Yes
[x] No
```
=> Fixing other reference to workspaceId

scripts/enable-aks-monitor.sh
Committed by mistake. 
```
[ ] Yes
[x] No
```
=> Fixing typo

templates/arm-mon-infra.json
Update with the changes to schema
```
[ ] Yes
[ x] No
```
=> update to match changes of schema file

variablegroups/SBOX-AKS-Common.json, variablegroups/SBOX-AKS-Tags.json, variablegroups/SBOX-KeyVault.json, variablegroups/scripts/get-all-variable-groups.sh
Removing the test var group and adding sandbox groups to test the pipeline before adding others.
```
[ ] Yes
[x] No
```
=> Adding Sandbox variables groups to test pipeline

README.md
Github doesn't like the [][] markup.
```
[ ] Yes
[x] No
```
=> Fix Read me makrup

variablegroups/AAT-AKS-Common.json, variablegroups/AAT-AKS-KeyVault.json, variablegroups/AAT-AKS-Tags.json
Fixes [AB#350](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/350)
```
[ ] Yes
[x] No
```
=> Adding AAT variable groups.

variablegroups/AAT-AKS-Common.json, variablegroups/AAT-AKS-KeyVault.json, variablegroups/AAT-AKS-Tags.json
=> fix DNS server and update as per script output

variablegroups/AAT-AKS-Common.json
Adding hmctspublic registry to AAT
```
[ ] Yes
[x] No
```
=> Adding hmctspublic registry to AAT

variablegroups/RPE-AKS-KeyVault.json
=> missing RPE variables actionGroupEmailRecievers and slack-webhook-url

templates/arm-mon-infra.json
Add link to slack notification
```
[ ] Yes
[ ] No
```
=> Add link to slack notification

variablegroups/RPE-AKS-Common.json
=> missing rpedev iaas ip

templates/arm-mon-custom-alerts.json
and causes unwanted alerts.
```
[ ] Yes
[x] No
```
=> Fixing timewindow as it doesn't make sense to run for a larger span

deployments/fluxcd/values.yaml, scripts/create-flux-githubkey-secret.sh
=> Removing need to restart flux pods on install

variablegroups/MGMT-SBOX-AKS-Common.json
=> Pe 154 - default vnet DNS point to Tactical dns

templates/appgw-arm.json, templates/arm-vnet-template.json, variablegroups/AAT-AKS-Common.json, variablegroups/DEMO-AKS-Common.json, variablegroups/ITHC-AKS-Common.json, variablegroups/PAPI-SBOX-AKS-Common.json, variablegroups/SBOX-AKS-Common.json
Fixes [AB#411](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/411) 
```
[ ] Yes
[x] No
```
=> Moving to Appgw V2

templates/appgw-arm.json
It might have worked in PR as i was giving value with quotes
```
[ ] Yes
[x] No
```
=> Fixing type

variablegroups/AAT-AKS-Common.json
Reverts hmcts/cnp-aks-rbac-pipelines#102
=> Revert "Update AAT-AKS-Common.json"

variablegroups/AAT-AKS-Common.json
=> cluster increase

variablegroups/AAT-AKS-Common.json
=> disabling the failed cluster

variablegroups/AAT-AKS-Common.json
Reverts hmcts/cnp-aks-rbac-pipelines#105
=> Revert "disabling the failed cluster"

variablegroups/PERFTEST-AKS-KeyVault.json, variablegroups/PERFTEST-AKS-Tags.json, variablegroups/PERTTEST-AKS-Common.json
=> update perftest variables

azure-pipelines.yml, team-config/sbox/all.yaml, terraform/.gitignore, terraform/app-gateway-module/config.tf, terraform/app-gateway-module/main.tf, terraform/app-gateway-module/variables.tf, terraform/main.tf, terraform/sbox.tfvars
AB#403
1. Convert pipeline to multistage build and add terraform
2. Add terraform code
3. Add team yaml code
There will be more PRs, to add more envs, remove old AGs, remove old AG config, separate team config out into separate files
```
[ ] Yes
[ ] No
```
=> Add config for app gw in sandbox

azure-pipelines.yml, devops-templates/terraform-apply-template.yaml, devops-templates/terraform-plan-template.yaml
AB#403
Extract step templates for terraform to make adding new environments easier
```
[ ] Yes
[ ] No
```
=> Convert to step template

azure-pipelines.yml, devops-templates/terraform-apply-template.yaml, devops-templates/terraform-plan-template.yaml, team-config/aat/all.yaml, team-config/ithc/all.yaml, team-config/perftest/all.yaml, terraform/ithc.tfvars, terraform/perftest.tfvars, terraform/stg.tfvars
[AB#453](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/453)
```
[ ] Yes
[ ] No
```
=> Add more envs

azure-pipelines.yml, terraform/app-gateway-module/main.tf
Fixes [AB#452](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/452)
Add diagnostic settings
```
[ ] Yes
[ ] No
```
=> Add diagnostic settings to new AGs

templates/arm-vnet-template.json, terraform/app-gateway-module/main.tf
Fixes [AB#461](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/461)
Fixes [AB#462](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/462)
If you're bored then see: https://tools.hmcts.net/confluence/display/RD/Resource+Naming+Convention+and+Pattern+Repository
```
[ ] Yes
[ ] No
```
=> Rename resources to match policy

variablegroups/PAPI-SBOX-AKS-Common.json
-
Updated PAPI-SBOX VNET IaaS subnet IP address.
```
[ ] Yes
[X] No
```
=> Updated PAPI-SBOX VNET IaaS subnet IP address.

azure-pipelines.yml, templates/arm-vnet-template.json
[AB#492](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/492)
Policy is failing because we don't have this...
```
[ ] Yes
[ ] No
```
=> Add route table to all subnets

templates/arm-aks-template.json, variablegroups/AAT-AKS-Common.json, variablegroups/DEMO-AKS-Common.json, variablegroups/ITHC-AKS-Common.json, variablegroups/MGMT-SBOX-AKS-Common.json, variablegroups/MI-SBOX-AKS-Common.json, variablegroups/PAPI-SBOX-AKS-Common.json, variablegroups/PERTTEST-AKS-Common.json, variablegroups/RPE-AKS-Common.json, variablegroups/SBOX-AKS-Common.json
=> Upgrading AKS version

variablegroups/PAPI-SBOX-AKS-Common.json
-
Update ACR in PAPI-SBOX-AKS-Common.json.
```
[ ] Yes
[X] No
```
=> Update ACR in PAPI-SBOX-AKS-Common.json

templates/arm-mon-custom-alerts.json, templates/arm-mon-metric-alerts.json
Fixes [AB#518](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/518)
So that SNOW can route the alerts...
Also tune a couple of alerts severity
```
[ ] Yes
[ ] No
```
=> Prefix all alerts with service offering

templates/arm-vnet-template.json, variablegroups/AAT-AKS-Common.json, variablegroups/DEMO-AKS-Common.json, variablegroups/ITHC-AKS-Common.json, variablegroups/MGMT-SBOX-AKS-Common.json, variablegroups/MI-SBOX-AKS-Common.json, variablegroups/PAPI-SBOX-AKS-Common.json, variablegroups/PERFTEST-AKS-Common.json, variablegroups/Prod-AKS-Common.json, variablegroups/RPE-AKS-Common.json, variablegroups/SBOX-AKS-Common.json
Applied workaround explained in here , as arm doesn't support iteration when length is 0.
https://docs.microsoft.com/en-us/azure/architecture/building-blocks/extending-templates/conditional-deploy#example-template
```
[ ] Yes
[x] No
```
=> Adding option to add aks nsg security rules for demo

templates/arm-mon-custom-alerts.json
[AB#523](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/523)
```
[ ] Yes
[ ] No
```
=> Fix alerts

variablegroups/Prod-AKS-Common.json
=> fix prod k8s version

variablegroups/AAT-AKS-Common.json
see if it help draft-store issue
=> Add another node to AAT

variablegroups/MI-SBOX-AKS-Common.json
Changing ip range for iaas subnet to the correct one 
```
[ ] Yes
[x] No
```
=> fixing ip for iaas subnet

variablegroups/MI-SBOX-AKS-Common.json
adding dns ip address to mi sbox cluster
```
[ ] Yes
[x] No
```
=> adding dns ip for mi sbox cluster

team-config/aat/all.yaml, team-config/ithc/all.yaml, team-config/perftest/all.yaml, team-config/prod/all.yaml, team-config/sbox/all.yaml
=> Add gw config for aks workshop

variablegroups/PERFTEST-AKS-Common.json
=> Increase perftest node count to 5

deployments/fluxcd/values.yaml, scripts/install-flux.sh
=> simplifying kustomize directory structure

team-config/aat/all.yaml, team-config/ithc/all.yaml, team-config/perftest/all.yaml, team-config/prod/all.yaml
DIV-5704 
To prepare for AKS switchover
```
[ ] Yes
[x] No
```
=> DIV-5704 - add missing Divorce apps

variablegroups/Prod-AKS-Common.json
In preparation for new apps next week
=> Scaling prod AKS cluster

team-config/aat/all.yaml
=> EthosAdded

team-config/aat/all.yaml
=> feat:added app gateway change for am - aat

team-config/aat/all.yaml, team-config/prod/all.yaml
=> Fixing s2s missing config

team-config/prod/all.yaml
Added ethos to prod.
```
[ ] Yes
[X] No
```
=> Added Ethos to prod

team-config/aat/all.yaml
=> Add gw config for bulk scan pay processor

team-config/aat/all.yaml, team-config/perftest/all.yaml, team-config/prod/all.yaml
https://tools.hmcts.net/jira/browse/PRO-6258
```
[ ] Yes
[ x] No
```
=> add probate orchestrator

team-config/perftest/all.yaml
=> adding s2s for perftest

variablegroups/SBOX-AKS-Common.json
=> Scale sbox to 3 nodes

templates/arm-vnet-template.json
=> Removing empty route tables

team-config/aat/all.yaml
=> Added divorce health monitor team config

team-config/aat/all.yaml
https://tools.hmcts.net/jira/browse/RDCC-478
https://tools.hmcts.net/jira/browse/RDCC-575
Adding Adding all 3 Ref Data apps into whitelis.
rd-professional-api, rd-user-profile-api, rd-profile-sync
```
[ ] Yes
[x] No
```
=> RDCC-478 Adding all 3 Ref Data apps into whitelist

team-config/aat/all.yaml, team-config/prod/all.yaml
https://tools.hmcts.net/jira/browse/RDCC-478
RDCC-478 Ref data apps entries for Prod 
```
[ ] Yes
[X] No
```
=> RDCC-478 Ref data apps entries for Prod 

team-config/ithc/all.yaml
DIV-5844 
```
[ ] Yes
[x] No
```
=> DIV-5844 - Added Divorce div-hm to ITHC

team-config/perftest/all.yaml
=> fix ccd perftest aks appgw

variablegroups/DEMO-AKS-Common.json, variablegroups/ITHC-AKS-Common.json, variablegroups/MGMT-SBOX-AKS-Common.json, variablegroups/MI-SBOX-AKS-Common.json, variablegroups/RPE-AKS-Common.json, variablegroups/SBOX-AKS-Common.json
=> fix acr name on few clusters

team-config/aat/all.yaml
=> Adding Submit Service App Gate way Config.

team-config/ithc/all.yaml, team-config/perftest/all.yaml, team-config/prod/all.yaml, team-config/sbox/all.yaml
=> Added probate apps to all env.

team-config/aat/all.yaml
https://tools.hmcts.net/jira/browse/BPS-838
add send letter service
```
[ ] Yes
[x] No
```
=> add send letter service

team-config/aat/all.yaml
Fixing broken tests
```
[ ] Yes
[x] No
```
=> Added cor and notif gateways

variablegroups/MGMT-SBOX-AKS-Common.json, variablegroups/MGMT-SBOX-AKS-KeyVault.json
[AB#608](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/608)
Updated MGMT Sbox values to match new subscription details
```
[ ] Yes
[ x] No
```
=> Updated mgmt-sbox values

team-config/aat/all.yaml
[Router: Create a new Micro service](https://tools.hmcts.net/jira/browse/BPS-794)
Adding `reform-scan/blob-router` component
```
[ ] Yes
[x] No
```
=> Add blob router component

variablegroups/AAT-AKS-Common.json, variablegroups/DEMO-AKS-Common.json, variablegroups/ITHC-AKS-Common.json, variablegroups/PERFTEST-AKS-Common.json
=> Upgrading k8s version on non prod clusters

variablegroups/Prod-AKS-Common.json
=> Fail over prod to 01 only

team-config/prod/all.yaml
https://tools.hmcts.net/jira/browse/BPS-868
add send letter
```
[ ] Yes
[x] No
```
=> add send letter to Prod

team-config/prod/all.yaml
https://tools.hmcts.net/jira/browse/BPS-867
add orchestrator to PROD
```
[ ] Yes
[x] No
```
=> add orchestrator to PROD

variablegroups/Prod-AKS-Common.json
=> Upgrading aks on prod 00

variablegroups/DEMO-AKS-Common.json
=> Fixing PIP for demo nsg settings

team-config/prod/all.yaml
Reverts hmcts/cnp-aks-rbac-pipelines#194
=> Revert "Fail over attempt 2"

team-config/prod/all.yaml
Reverts hmcts/cnp-aks-rbac-pipelines#199
=> Revert "Revert "Fail over attempt 2""

team-config/prod/all.yaml
Reverts hmcts/cnp-aks-rbac-pipelines#201
=> Add traffic back to 00

team-config/prod/all.yaml
Serving traffic only to prod 00
```
[ ] Yes
[x] No
```
=> Serving traffic only for prod 00

team-config/prod/all.yaml
Reverts hmcts/cnp-aks-rbac-pipelines#203
=> Revert "Serving traffic only for prod 00"

team-config/aat/all.yaml
=> Whitelisting the bulkscanning-api url for fees-pay

azure-pipelines.yml, templates/arm-vnet-template.json
[AB#594](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/594)
```
[ ] Yes
[ ] No
```
=> Fix fail when no hub to peer with

team-config/prod/all.yaml
=> Added bulkscanning-API to route traffic to AKS pod

team-config/aat/all.yaml
=> Whitelisting for Payment/Fees register api

team-config/aat/all.yaml
=> Remove duplicate payment entry

azure-pipelines.yml, templates/vars/cftptl-intsvc.json, variablegroups/CFTPTL-AKS-Common.json, variablegroups/CFTPTL-AKS-KeyVault.json, variablegroups/CFTPTL-AKS-Tags.json
[AB#644](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/644)
```
[ ] Yes
[ ] No
```
=> Add cftptl

team-config/prod/all.yaml
https://tools.hmcts.net/jira/browse/BPS-891
add bulk-scan payment-processor
```
[ ] Yes
[x] No
```
=> add bulk-scan payment-processor

team-config/perftest/all.yaml
=> [AK] Add work-allocation configuration

variablegroups/AAT-AKS-Common.json
=> Scale up aat aks clusters to 16 nodes

team-config/ithc/all.yaml, team-config/perftest/all.yaml, team-config/sbox/all.yaml
adding app gw config for ref data
```
[ ] Yes
[x ] No
```
=> config: adding app gw config for ref data

variablegroups/DEMO-AKS-Common.json
=> add 2 nodes to demo

variablegroups/SBOX-AKS-Common.json
Update node count to 7 from 5
```
[ ] Yes
[ x] No
```
=> update node count

variablegroups/SBOX-AKS-Common.json
Upgrade version of sbox cluster to 1.15.5 which is GA now
=> update k8s version sbox

team-config/ithc/all.yaml
=> Add appgw ccd ithc

variablegroups/CFTPTL-AKS-Common.json, variablegroups/DEMO-AKS-Common.json, variablegroups/ITHC-AKS-Common.json, variablegroups/MGMT-SBOX-AKS-Common.json, variablegroups/RPE-AKS-Common.json
=> upgrade k8s version

variablegroups/CFTPTL-AKS-Common.json, variablegroups/DEMO-AKS-Common.json, variablegroups/ITHC-AKS-Common.json, variablegroups/MGMT-SBOX-AKS-Common.json, variablegroups/RPE-AKS-Common.json, variablegroups/SBOX-AKS-Common.json
=> upgrade k8s version to 1.15.7

team-config/perftest/all.yaml
=> APPGW Perftest CCD

team-config/aat/all.yaml, team-config/prod/all.yaml
[AB#717](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/717)
=> Add div-cfs to LB

team-config/prod/all.yaml, templates/vars/aks/prod.json, variablegroups/Prod-AKS-Common.json
=> upgrade prod cluster

team-config/prod/all.yaml
=> add both clusters

templates/arm-vnet-template.json
This is for cftptl iaas where we need agents to be access databse. 
```
[ ] Yes
[x] No
```
=> Adding service end points for iaas subnet

team-config/aat/all.yaml, team-config/ithc/all.yaml, team-config/perftest/all.yaml, team-config/prod/all.yaml
=> Add xui team config

team-config/prod/all.yaml
=> removing traffic from prod 01

team-config/prod/all.yaml
This reverts commit 2f7994bd0a6819cb754079ab1f26e8f9b6212806.
```
[ ] Yes
[ ] No
```
=> Revert "removing traffic from prod 01 (#249)"

scripts/install-flux.sh
=> Upgrading helm operator

team-config/prod/all.yaml
=> Remove traffic from prod 01

team-config/prod/all.yaml
Reverts hmcts/cnp-aks-rbac-pipelines#253
=> Revert "Remove traffic from prod 01"

team-config/prod/all.yaml
=> Remove traffic from prod 00

scripts/install-flux.sh, variablegroups/AAT-AKS-Common.json, variablegroups/CFTPTL-AKS-Common.json, variablegroups/DEMO-AKS-Common.json, variablegroups/ITHC-AKS-Common.json, variablegroups/MGMT-SBOX-AKS-Common.json, variablegroups/PERFTEST-AKS-Common.json, variablegroups/Prod-AKS-Common.json, variablegroups/SBOX-AKS-Common.json
=> Cleaning up old helm config

team-config/prod/all.yaml
Reverts hmcts/cnp-aks-rbac-pipelines#255
=> Revert "Remove traffic from prod 00"

team-config/aat/all.yaml
https://tools.hmcts.net/jira/browse/EM-2348
add gateway for em-showcase to enable access to it on AAT
```
[ ] Yes
[X] No
```
=> add gateway for em-showcase frontend app

scripts/install-flux.sh
=> Upgrading to latest helm operator

team-config/aat/all.yaml
=> RDM-7389 add test-stubs-service

team-config/aat/all.yaml
=> Take aks  aat-01 out of service

team-config/aat/all.yaml
=> Restore traffic to aat-01

team-config/perftest/all.yaml
https://tools.hmcts.net/jira/browse/BPS-1030
```
[ ] Yes
[ x] No
```
=> Added gw config for bulk scan services in perftest

templates/vars/vnet/demo.json
=> Changing DNS Server for Demo

team-config/sbox/all.yaml
SIDM-3609 - add idam ms endpoints to sandbox appgw
https://tools.hmcts.net/jira/browse/SIDM-3609
add idam ms endpoints to sandbox appgw
```
[ ] Yes
[x] No
```
=> SIDM-3609 - add idam ms endpoints to sandbox appgw

team-config/perftest/all.yaml
=> Updated sscs cor-backend

team-config/ithc/all.yaml
add idam-ithc appgw backends
```
[ ] Yes
[x] No
```
=> feat(idam-ithc): add appgw backends

team-config/aat/all.yaml, team-config/ithc/all.yaml, team-config/perftest/all.yaml, team-config/prod/all.yaml
adding new services jrd-jud-data-load and judicial-api names in aat,ithc and perftest environments 
```
[ ] Yes
[ X] No
```
=> adding new service rd-judicial-api name in aat,ithc and perftest environments 

team-config/ithc/all.yaml, team-config/sbox/all.yaml, terraform/app-gateway-module/main.tf
https://tools.hmcts.net/jira/browse/SIDM-3686
Add configuration option for cookie based affinity
```
[ ] Yes
[x] No
```
=> SIDM-3686 - Add configuration option for cookie based affinity

team-config/aat/all.yaml
=> Added iap-frontend to aat

team-config/demo/all.yaml
Adding Divorce products to demo hostname
=> Adding Divorce products to demo hostname

team-config/aat/all.yaml
[AB#791]
```
[ ] Yes
[x] No
```
=> Add appgw config for cmc claim-store

team-config/aat/all.yaml, team-config/ithc/all.yaml, team-config/perftest/all.yaml, team-config/prod/all.yaml
[AB#791]
```
[ ] Yes
[x] No
```
=> Cmc claimstore appgw

team-config/perftest/all.yaml
https://tools.hmcts.net/jira/browse/SIDM-3774
idam-perftest backend listeners
```
[ ] Yes
[x] No
```
=> SIDM-3774 - idam-perftest backend listeners

team-config/aat/all.yaml
=> add adoption product and component to team config

team-config/demo/all.yaml
N/A
IA Team apps
```
[ ] Yes
[x] No
```
=> IA Team apps

team-config/prod/all.yaml
[AB#806]
```
[ ] Yes
[x] No
```
=> Drain prod-01 aks for upgrade

team-config/prod/all.yaml
[AB#806]
```
[ ] Yes
[x] No
```
=> Restore prod-01-aks

team-config/prod/all.yaml
[AB#806]
```
[ ] Yes
[x] No
```
=> Drain prod-00-aks

team-config/prod/all.yaml
[AB#806]
```
[ ] Yes
[x] No
```
=> Restore prod-00-aks

team-config/aat/all.yaml
https://tools.hmcts.net/jira/browse/SIDM-3820
AKS backend AppGw listeners to aat
```
[ ] Yes
[ X ] No
```
=> adding in IDAM to all envs

team-config/aat/all.yaml, team-config/ithc/all.yaml, team-config/perftest/all.yaml, team-config/prod/all.yaml
added entries for judicial data load
```
[ ] Yes
[ x] No
```
=> config: added entries for judicial data load

team-config/demo/all.yaml
=> Added Ethos to demo

team-config/README.md
AB#833
Added a readme file explaining users where the configuration for the app gw has been moved. 
```
[ ] Yes
[x] No
```
=> Added documentation for migrated appgw module

deployments/fluxcd/values.yaml, deployments/sealed-secrets/values.yaml, scripts/install-sealed-secrets.sh
=> Adding resource limits for flux and sealed secrets

.gitignore, templates/arm-vnet-template.json, templates/vars/vnet/sbox.json
[AB#816]
```
[ ] Yes
[x] No
```
=> Add vnet linking for private dns

templates/arm-vnet-template.json, templates/vars/vnet/sbox.json
[AB#816]
```
[ ] Yes
[x] No
```
=> Fix private dns zones parameter

templates/arm-vnet-template.json
[AB#816]
```
[ ] Yes
[x] No
```
=> Add arm vnet copy condition

templates/vars/vnet/aat.json, templates/vars/vnet/cftptl-intsvc.json, templates/vars/vnet/cftsbox-intsvc.json, templates/vars/vnet/demo.json, templates/vars/vnet/ithc.json, templates/vars/vnet/perftest.json, templates/vars/vnet/prod.json, templates/vars/vnet/sbox.json
[AB#883]
```
[ ] Yes
[x] No
```
=> Add vnet linking

templates/arm-vnet-template.json
[AB#883]
```
[ ] Yes
[x] No
```
=> Update vnet linking arm api to supported one

templates/vars/vnet/sbox.json
[AB#883]
```
[ ] Yes
[x] No
```
=> Add sbox vnet linking to platform zone

templates/vars/aks/prod.json
Lots of new apps added recently and few more coming in next week.
```
[ ] Yes
[x] No
```
=> Scaling up prod

templates/vars/vnet/prod.json
[AB#885]
```
[ ] Yes
[x] No
```
=> Fix prod zone private dns linking

templates/vars/vnet/aat.json
=> Swapping AAT AKS over to private DNS

templates/vars/vnet/sbox.json
=> Add vnet linking for idam sprod + saat

scripts/install-flux.sh
=> upgrading flux

scripts/install-flux.sh
=> Upgrade helm operator

variablegroups/DEV-AKS-Common.json, variablegroups/DEV-AKS-KeyVault.json
=> New Dev: remove name override, fix endpoint id

templates/vars/aks/sbox.json
=> Use vmss + k8s 1.16 in sbox

templates/vars/aks/demo.json
=> scalup demo

templates/vars/aks/aat.json
=> Scale up aat

templates/vars/aks/prod.json
Scaling production aks cluster
=> scale prod

roles/edit-role-binding.yaml, variablegroups/AAT-AKS-Common.json, variablegroups/AKS-Common.json, variablegroups/CFTPTL-AKS-Common.json, variablegroups/DEMO-AKS-Common.json, variablegroups/DEV-AKS-Common.json, variablegroups/ITHC-AKS-Common.json, variablegroups/MGMT-SBOX-AKS-Common.json, variablegroups/PERFTEST-AKS-Common.json, variablegroups/Prod-AKS-Common.json, variablegroups/SBOX-AKS-Common.json
=> Add the edit crb for use in preview env

templates/arm-aks-template.json, templates/vars/aks/aat.json, templates/vars/aks/perftest.json, templates/vars/aks/prod.json
=> Use k8s 1.16 + calico in aat00

variablegroups/DEV-AKS-Common.json
*Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ x] No
```
=> change override name and slack channel to preview

templates/arm-aks-template.json
=> Update aks template network plugin

scripts/create-developer-roles.sh
=> Fix role script

templates/vars/vnet/preview.json
=> Add missing dns zone link

templates/vars/aks/preview.json
=> Scale preview

README.md
=> Update docs - add how to update k8s version

templates/vars/aks/demo.json
=> Upgrade demo

deployments/namespaces.yaml, roles/dynatrace-cluster-role-binding.yaml, scripts/register-cluster-with-dynatrace.sh, variablegroups/AAT-AKS-Common.json, variablegroups/PERFTEST-AKS-Common.json
=> script to autoregister k8s clusters in dynatrace

deployments/fluxcd/values.yaml
=> Increase flux git timeout

scripts/install-flux.sh
=> Add common overlay directory to flux

templates/vars/aks/aat.json, templates/vars/aks/cftptl-intsvc.json, templates/vars/aks/cftsbox-intsvc.json, templates/vars/aks/demo.json, templates/vars/aks/ithc.json, templates/vars/aks/ldata.json, templates/vars/aks/perftest.json, templates/vars/aks/preview.json
[AB#978](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/978)
=> Update all nonprod clusters

deployments/fluxcd/values.yaml
Tested on Sandbox deployment - https://dev.azure.com/hmcts/CNP/_releaseProgress?_a=release-pipeline-progress&releaseId=5384
```
[ ] Yes
[ x] No
```
=> Remove mounting acr creds for flux

templates/arm-aks-template.json, templates/vars/aks/aat.json, templates/vars/aks/cftptl-intsvc.json, templates/vars/aks/cftsbox-intsvc.json, templates/vars/aks/demo.json, templates/vars/aks/ithc.json, templates/vars/aks/ldata.json, templates/vars/aks/perftest.json, templates/vars/aks/preview.json, templates/vars/aks/prod.json, templates/vars/aks/sbox.json
[AB#978](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/978)
```
[ ] Yes
[ ] No
```
=> Update prod to 1.17.7 and Azure CNI

scripts/install-flux.sh
=> Upgrade flux

variablegroups/SBOX-AKS-Common.json
- [ x ] commit messages are meaningful and follow good commit message guidelines
Add NSG rule to sbox environment to permit connectivity from the sbox bastion host
```
[ ] Yes
[ x ] No
```
=> add aks sbox nsg rule for bastion host

templates/vars/aks/cftptl-intsvc.json, templates/vars/aks/cftsbox-intsvc.json
[[AB#1032](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/1032)]
```
[ ] Yes
[x] No
```
=> Add capacity to cftptl + cftsbox clusters

templates/vars/aks/prod.json
Has been manually scaled already, updating in code
```
[ ] Yes
[ x] No
```
=> Scale prod clusters up to 28 (csi driver pods are  also being deployed)

templates/vars/aks/cftptl-intsvc.json
=> Add capacity to Jenkins AKS cluster

roles/edit-role-binding.yaml, roles/reader-role-binding.yaml
Custom resources weren't included as part of edit role
```
[ ] Yes
[ x] No
```
=> add in custom resources for preview env

variablegroups/LDATA-AKS-Common.json
=> enable DT on LDATA

roles/edit-role-binding.yaml, roles/reader-role-binding.yaml
Added so devs have access to this other custom resource on Preview.
```
[ ] Yes
[x ] No
```
=> add serviceinstances

templates/vars/aks/perftest.json
=> Scale up perftest

templates/vars/aks/perftest.json
Reverts hmcts/cnp-aks-rbac-pipelines#412
=> Revert "Scale up perftest"

variablegroups/DEMO-AKS-Common.json
[[AB#1119](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/1119)]
```
[ ] Yes
[ ] No
```
=> Update demo vnet ip range

templates/vars/aks/perftest.json
=> Increase node count on perftest

templates/vars/aks/ithc.json
Finrem, exui were added. Small scale up needed.
```
[ ] Yes
[x ] No
```
=> ithc scaleup

templates/vars/aks/prod.json
Currently both clusters are running at high CPU.
```
[ ] Yes
[x] No
```
=> Scale up prod

templates/vars/aks/preview.json
=> node autoscaler changes

templates/vars/aks/aat.json, templates/vars/aks/perftest.json
https://dev.azure.com/hmcts/Platform%20Engineering/_workitems/edit/1112
```
[ ] Yes
[x] No
```
=> Enabling autoscaler on aat

templates/vars/aks/ithc.json
=> node autoscaler changes on ithc

templates/vars/aks/prod.json
=> node autoscaler changes for prod

templates/vars/aks/cftptl-intsvc.json, templates/vars/aks/prod.json
=> node autoscaler changes for cftptl-intsvc

templates/vars/aks/preview.json, templates/vars/aks/sbox.json
=> correcting the vm sizes

scripts/install-sealed-secrets.sh
Temporarily moving to hmctspublic till sealed secrets chart is moved.
```
[ ] Yes
[x] No
```
=> Moving sealed secrets to hmctspublic

deployments/fluxcd/helm-operator-values.yaml
=> remove stable helm

roles/edit-role-binding.yaml, roles/reader-role-binding.yaml
Add permissions
```
[ ] Yes
[ x] No
```
=> Add access for devs to view secretproviderclasses

templates/vars/aks/cftptl-intsvc.json, templates/vars/aks/demo.json, templates/vars/aks/perftest.json
Add perftest, demo & cftptl-intsvc managed identity values
```
[ ] Yes
[X] No
```
=> Add perftest, demo & cftptl-intsvc managed identity values

templates/vars/vnet/cftptl-intsvc.json
=> linking private dns zone for postgres

templates/vars/aks/demo.json
=> Upgrading demo

templates/vars/aks/ldata.json
Required var updates for AKS rebuild to include
- AKS Managed Identity
- AKS Version Update
- Scalesets
- Ephemeral disk
Jira raised for IAM DTSPO-891
```
[ ] Yes
[X] No
```
=> Update ldata vars

templates/arm-aks-template.json, templates/vars/aks/aat.json, templates/vars/aks/cftptl-intsvc.json, templates/vars/aks/cftsbox-intsvc.json, templates/vars/aks/demo.json, templates/vars/aks/ithc.json, templates/vars/aks/ldata.json, templates/vars/aks/perftest.json, templates/vars/aks/preview.json, templates/vars/aks/prod.json, templates/vars/aks/sbox.json
Remove ephemeral vars and update default OS Disk value
```
[ ] Yes
[X] No
```
=> Remove ephemeral vars and update default OS Disk value

roles/edit-role-binding.yaml
add devs to deprovision instances
=> add devs to deprovision instances

templates/vars/aks/sbox.json
Update to access hmctssandbox AKS MI rework
```
[ ] Yes
[X] No
```
=> Update to access hmctssandbox AKS MI rework

templates/vars/vnet/aat.json, templates/vars/vnet/cftsbox-intsvc.json, templates/vars/vnet/demo.json, templates/vars/vnet/ithc.json, templates/vars/vnet/ldata.json, templates/vars/vnet/perftest.json, templates/vars/vnet/preview.json, templates/vars/vnet/prod.json, templates/vars/vnet/sbox.json
Already configured - looks to be manual for a number of these vnets. Adding into code for reference
```
[ ] Yes
[X] No
```
=> linking vnet to postgres private dns zone

variablegroups/ITHC-AKS-Common.json
Update ITHC IP addressing
```
[ ] Yes
[X] No
```
=> Update ITHC IP addressing

templates/arm-aks-template.json, templates/vars/aks/aat.json
https://docs.microsoft.com/en-us/azure/aks/uptime-sla
https://docs.microsoft.com/en-us/azure/templates/microsoft.containerservice/2021-02-01/managedclusters?tabs=json#ManagedClusterSKU
=> Enable paid sku for more HA in AKS API server

scripts/create-aks-load-balancer-publicip-prefix.sh
add --zone to fix pipeline error
- sbox release ran successful 
- needs az upgrade in script due to az cli task is v2.20.0, need v2.21 or errors out with "ERROR: unrecognized arguments: 2 3"
```
[ ] Yes
[X] No
```
=> Update zones pip to fix pipeline error

templates/vars/aks/prod.json
https://tools.hmcts.net/jira/browse/DTSPO-1956
Adding uptime SLA to prod
```
[ ] Yes
[x ] No
```
=> adding uptime sla to prod

templates/vars/aks/cftsbox-intsvc.json, templates/vars/aks/sbox.json
Updating AKS from 1.19.6 to 1.19.7
```
[ ] Yes
[X ] No
```
=> updating AKS version

templates/vars/vnet/cftptl-intsvc.json
=> DTSPO-1454 add SDS Dev route to palo nonprod

templates/vars/vnet/cftptl-intsvc.json
=> add vnet link dev.platform

scripts/create-aks-load-balancer-publicip-prefix.sh
Remove temporary az upgrade as new version is available
```
[ ] Yes
[X] No
```
=> Remove temporary az upgrade

templates/vars/aks/ithc.json
https://tools.hmcts.net/jira/browse/DTSPO-2033
Updating aks version ithc
```
[ ] Yes
[X ] No
```
=> Updating aks version ithc

templates/vars/aks/aat.json
Updating AKS version in AAT from 1.19.6 to 1.19.7
```
[ ] Yes
[ X] No
```
=> Updating AKS version in AAT

templates/vars/vnet/prod.json
CFT AKS Traffic to flow through Palo Alto
- Will be merged during proposed change window 12/04
```
[ ] Yes
[X] No
```
=> CFT AKS Traffic to flow through Palo Alto

templates/vars/aks/demo.json, templates/vars/aks/preview.json, templates/vars/aks/sbox.json
https://tools.hmcts.net/jira/browse/DTSPO-2033
Upgraded of AKS for Demo env.
```
[ ] Yes
[ x] No
```
=> Updating AKS version in Demo

templates/vars/vnet/sbox.json
https://tools.hmcts.net/jira/browse/DTSPO-2279
=> DTSPO-2279 Update sbox env with the entry for cvp storage privatelink  

templates/vars/aks/cftptl-intsvc.json, templates/vars/aks/perftest.json
https://tools.hmcts.net/jira/browse/DTSPO-2033
Updating AKS to 1.19.7
```
[ ] Yes
[ X] No
```
=> update to AKS version in perf test & management environment

variablegroups/AAT-AKS-Common.json
https://tools.hmcts.net/jira/browse/DTSPO-2463
Update AAT IP ranges
```
[ ] Yes
[X] No
```
=> Update AAT IP ranges

variablegroups/AAT-AKS-Common.json
Reverts hmcts/cnp-aks-rbac-pipelines#480
=> Revert "Update AAT IP ranges"

templates/vars/aks/prod.json
https://tools.hmcts.net/jira/browse/DTSPO-1894
Update prod to use 1.19.7 version of AKS.
```
[ ] Yes
[x ] No
```
=> updated prod aks version to 1.19.7

templates/vars/aks/aat.json
https://tools.hmcts.net/jira/browse/DTSPO-4191
Update to AKS version for AAT
```
[ ] Yes
[ X] No
```
=> update to AKS version being used for AAT

variablegroups/AAT-AKS-KeyVault.json, variablegroups/SBOX-AKS-KeyVault.json
https://tools.hmcts.net/jira/browse/DTSPO-4191
updated endpoint id for aat
```
[ ] Yes
[ x] No
```
=> updated service endpoint id for aat

templates/vars/aks/prod.json
https://tools.hmcts.net/jira/browse/DTSPO-4191
Update to AKS version for Prod
```
[ ] Yes
[X ] No
```
=> update to AKS version for Prod

variablegroups/Prod-AKS-KeyVault.json
=> fix service end point id for prod

variablegroups/DEV-AKS-KeyVault.json
=> fix dev service endpoint

templates/vars/aks/preview.json
Update preview aks version
```
[ ] Yes
[X] No
```
=> Update preview aks version

scripts/enable-aks-monitor.sh
no idea if we'll ever re-deploy with this but just in case
=> Cheaper logs

templates/arm-vnet-template.json, templates/vars/vnet/prod.json
Add appGw routetable to Production
- Return cftptl route via Production Palo
```
[ ] Yes
[X] No
```
=> Add appGw routetable to Production

templates/vars/aks/demo.json
Upgraded AKS version to v1.21.7 for demo env.
```
[ ] Yes
[x] No
```
=> update aks version for demo env

templates/vars/aks/prod.json
Update min and max nodecount for Production
```
[ ] Yes
[X] No
```
=> Update min and max nodecount for Production

scripts/install-sealed-secrets.sh
=> Sealed secrets for prod deploy

scripts/install-flux.sh
Updated bootstrap install flux script to install version 1.4.2 instead of 1.2.0.
```
[ ] Yes
[x] No
```
=> updated flux version 
