hmcts/cnp-aks-rbac-pipelines

templates/arm-mon-infra.json
google api integration stopped working, it was replaced with link provided with alert payload
=> logic app fix - removed google api integration

templates/arm-mon-infra.json
remove link to results as it is to long and breaks slack message
=> RPE-1105 - remove link to results

scripts/install-tiller.sh
pipeline is failing with an error referring to old pod .
Error: forwarding ports: error upgrading connection: unable to upgrade connection: pod not found ("tiller-deploy-55dcff6679-bgpzr_kube-system")
```
[ ] Yes
[x] No
```
=> Adding sleep to let helm init after reset

scripts/create-azure-file-share.sh
- add two file shares to support 2 clusters
- store storage account key instead of entire connection string
=> 2nd NeuVector file share

deployments/weave-flux/values.yaml
Enabling experimental feature for flux to test kustomize. This doesn't break/change anything existing till it finds manifest files. It is safe to enable on other clusters as well.
```
[ ] Yes
[x] No
```
=> Enabling experimental feature for flux to test kustomize

scripts/remove-dashboard.sh
Fixes [AB#304](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/304)
Tried on sbox with PR build and works :
https://dev.azure.com/hmcts/CNP/_releaseProgress?releaseId=1760&_a=release-environment-logs&environmentId=6191
```
Atrocitus:~ praveenakainos.com$ az aks browse --resource-group sbox-01-rg --name sbox-01-aks --subscription b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb
The kube-dashboard addon was disabled for this managed cluster.
To use "az aks browse" first enable the add-on
by running "az aks enable-addons --addons kube-dashboard".
Atrocitus:~ praveenakainos.com$ az aks browse --resource-group sbox-00-rg --name sbox-00-aks --subscription b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb
The kube-dashboard addon was disabled for this managed cluster.
To use "az aks …
```
=> Fixing disabling dashboard

scripts/sonobuoy-test.sh
Adding sonobuoy to perform conformance tests , this will help us validate the cluster is all good after rolling out the change. See https://github.com/heptio/sonobuoy . Note that the K8s conformance tests run for more than an hour and E2E tests run for about 12 hours. So, this needs to be used sensibly. 
```
[ ] Yes
[x] No
```
=> Adding sonobuoy to testing clusters

scripts/sonobuoy-test.sh
Fixing path as Azure Devops doesn't add go to path
```
[ ] Yes
[x] No
```
=> Adding go to path

variablegroups/DEMO-AKS-Common.json, variablegroups/MI-SBOX-AKS-Common.json, variablegroups/PAPI-SBOX-AKS-Common.json, variablegroups/SBOX-AKS-Common.json
=> Fixing service connection names as they are renamed now in azure devops

terraform/app-gateway-module/secret.tf, terraform/app-gateway-module/variables.tf, terraform/ithc.tfvars, terraform/main.tf, terraform/sbox.tfvars, terraform/stg.tfvars, terraform/test.tfvars
Not sure how are we adding the secret to the keyvault. I couldn't find any so added the snippet to add the secret within the app gateway module. As it makes sense to add the secret right in the module when the gateway is created.
```
[ ] Yes
[X] No
```
=> add private ip to keyvault

scripts/remove-dashboard.sh, templates/arm-aks-template.json
Currently, API server is restarting when disabling cluster although its already disabled. Anyway, there is no point just keeping this separate in an extra step.
```
[ ] Yes
[x] No
```
=> Moving disable dashboard to arm template

templates/arm-aks-template.json, variablegroups/AAT-AKS-Common.json, variablegroups/DEMO-AKS-Common.json, variablegroups/ITHC-AKS-Common.json, variablegroups/MGMT-SBOX-AKS-Common.json, variablegroups/MI-SBOX-AKS-Common.json, variablegroups/PAPI-SBOX-AKS-Common.json, variablegroups/PERFTEST-AKS-Common.json, variablegroups/RPE-AKS-Common.json, variablegroups/SBOX-AKS-Common.json
1.13.7 version is no more supported.
```
[ ] Yes
[x] No
```
=> Bumping AKS version

team-config/prod/all.yaml
Add the Evidence Management team products. Note that the dm product hasn't been created yet.
=> Add evidence management team products

templates/arm-mon-infra.json
[AB#608](https://dev.azure.com/hmcts/90472b63-dc8d-4ae6-8819-a32bd211e914/_workitems/edit/608)
Limit to 12 characters for action group short name, because of the naming conventions we've ended up with an env called cftsbox-intsvc, which is too long.
```
[ ] Yes
[ ] No
```
=> Truncate action group short name

templates/vars/aks/aat.json
It is running 18 currently, which isn't enough for idam pods.
```
[ ] Yes
[x] No
```
=> Scale up aat

templates/vars/aks/perftest.json
Unable to restart  pods.
```
[ ] Yes
[x] No
```
=> Adding 2 nodes to perftest

scripts/install-flux.sh
- Changes to flux are maintained at both places currently.
- went there to add `acr-credentials` change which i missed before 
- Label was also different for flux to tag the repo (it was sandbox instead of sandbox-00-aks)
- Flux doesnt need to be installed in bootstrap, it needs helm operator and sealed secrets controller installed ahead ( i will swap sealed secrets in release pipeline)
```
[ ] Yes
[x] No
```
=> Install flux from flux-config patches

scripts/delete-aks-iam.sh, templates/arm-aks-template.json, templates/vars/aks/aat.json, templates/vars/aks/cftsbox-intsvc.json, templates/vars/aks/ithc.json, templates/vars/aks/preview.json, templates/vars/aks/prod.json, templates/vars/aks/sbox.json
Swapping AKS from service principals to managed identities &  AAD V2
DevOps user stories:-
1138 - Update Azure DevOps AKS pipeline task group for AADv2 cluster upgrade
1133 - Automation of IAM permissions required as part of AKS Managed Identity
```
[X] Yes
[ ] No
```
=> Changes to enable managed identity for AKS and aadprofile to managed

templates/arm-aks-template.json, templates/vars/aks/aat.json, templates/vars/aks/cftptl-intsvc.json, templates/vars/aks/cftsbox-intsvc.json, templates/vars/aks/demo.json, templates/vars/aks/ithc.json, templates/vars/aks/perftest.json, templates/vars/aks/preview.json, templates/vars/aks/prod.json, templates/vars/aks/sbox.json
- Add ephemeral disk config and vars
- Upgrade K8s version to 1.19.6 which is latest GA
- Update apiVersion of Microsoft.ContainerService/managedClusters to support Ephemeral Disk
- Removal of "enableAzureRBAC": true within AADProfile due to it causing an issue. Wasn't noticed before as previous apiVersion did not actually support enableAzureRBAC (reviewed apiVersion doc to reflect this)
Currently these changes are deployed to sbox00, sbox01 & cftsbox-intsvc-00-aks
```
[ ] Yes
[X] No
```
=> add ephemeral disk config and vars

templates/arm-vnet-template.json, templates/vars/vnet/aat.json, templates/vars/vnet/cftptl-intsvc.json, templates/vars/vnet/cftsbox-intsvc.json, templates/vars/vnet/demo.json, templates/vars/vnet/ithc.json, templates/vars/vnet/ldata.json, templates/vars/vnet/perftest.json, templates/vars/vnet/preview.json, templates/vars/vnet/prod.json, templates/vars/vnet/sbox.json
- Internet traffic to Palo Alto
- Demo environment not included for now
- Swapped route table to array/copy for ease of use, in future it is planned to add additional routes for private IP routing
- Removed ITHC hub reference as it has another route assigned with different name
- Added routetableName parameter due to ITHC having a different route table assigned and private IP range
Raising PR for review, all envs applied to except for Production Jenkins & Production. Will merge once this is complete
```
[ ] Yes
[X] No
```
=> Internet traffic to Palo Alto with some additional fixes

templates/vars/aks/demo.json, templates/vars/aks/ithc.json, templates/vars/aks/perftest.json, templates/vars/aks/prod.json, templates/vars/aks/sbox.json
We are seeing that having less min nodes is causing many helm releases to fail triggering autoscaler during cluster rebuilds. Reviewed the mins to be closer to the average if not same.
- AAT  - Current Min - 30 , Current Avg- 32, New Min -  30 (Unchanged)
- Prod- Current Min - 30, Current Avg- 41, New Min -  40
- Demo - Current Min - 10, Current Avg- 34, New Min -  30
- ITHC - Current Min - 10, Current Avg- 28, New Min -  25
- Perftest - Current Min- 20, Current avg- 40, New Min - 38
- Sandbox - Current Min - 10, Current  Avg - 10 . Reduced it to 6.
- PTL, MGMT SBOX - they look fine and running at current min nodes.
```
[ ] Yes
[x] No
```
=> Fix min nodes on aks clusters

templates/vars/vnet/cftptl-intsvc.json
Required to connect to perftest.platform.hmcts.net dns
Currently it is routing via Production Palo, needs to route to non-prod palo to where cft-perftest is peered to.
```
[ ] Yes
[X] No
```
=> Required to connect to perftest.platform.hmcts.net dns

templates/vars/aks/demo.json
Updated AKS version as 1.19.7 is not supported in region.
```
[ ] Yes
[x ] No
```
=> updated AKS version
